@host = http://localhost:5201
POST {{host}}/auth/register
Content-Type: application/json

{
    "FirstName": "Amichai",
    "LastName ": "Mantinband",
   "email": "amichai@mantinband.com",
    "password": "Amiko1232!"
}