@host = http://localhost:5201
POST {{host}}/auth/register
Content-Type: application/json

{
    "FirstName": "Dzenan",
    "LastName": "Krlic",
   "email": "dzenankrlic@gmail.com",
    "password": "Dzk123!"
}